name: ci-main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest] # macos-latest, windows-latest
        node: [16]

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Checkout
        uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ matrix.os }}-node-v${{ matrix.node }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/pnpm-lock.yaml')) }}

      - name: Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: corepack enable && pnpm install

      - name: Prepare
        run: npm run dev:prepare

      - name: Lint
        run: npm run lint

      - name: Test types
        run: npm run test:types

      - name: Prepack
        run: npm run prepack
